name: CI - Spring Boot

on:
  push:
    branches: [main, '**']   # '**' matches all branches
  pull_request:
    branches: [main]         # optional, runs on PRs to main


jobs:
  build:
    runs-on: ubuntu-latest

    services:
          mongodb:
            image: mongodb/mongodb-atlas-local
            ports:
              - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: temurin
          cache: maven

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB..."
          until docker exec $(docker ps -qf "ancestor=mongo:7.0") mongosh --eval 'db.runCommand({ ping: 1 })'; do
            sleep 2
          done

      - name: Build and test
        run: mvn clean verify
        working-directory: back-end/Policyme
